### ISSUE TITLE
Pixel 7a, Graphene OS 14: Beta crashes on Startup

### ISSUE THREAD

**Issue by DamageIncorporated** [Team-Ladefuchs/ladefuchs-react-native#28]
Hey,

I've tried to install the latest beta today, going the "keine Lust auf Play Store?" route on the website.

I'm on a Pixel 7a with Graphene OS 14, Play Services are disabled (only available on a separate user account).

The f-droid version 2.0.7 runs as expected, but the beta crashes instantly 😥

I'd like to provide additional information, but as regular user I need easy instructions, preferably in german.😅

**Comment by DominicWrege** [comment]
Das Repo ist eher für Entwickler gedacht, also nicht wirklich für normale Nutzer ausgelegt.

Hi hast du schon eine .env-Datei mit dem API-Token erstellt, wie es in der README steht? Ohne die geht’s leider nicht.

Wenn du keinen Bock auf den Play Store hast, kannst du auch die F-Droid-Version nehmen. Wir sind gerade dabei, Version 3.0 für F-Droid fertigzustellen.

**Comment by DominicWrege** [comment]
Wir haben feedback@ladefuchs.app oder den CleanElectric [Slack](https://join.slack.com/t/cleanelectric/shared_invite/enQtOTQyNzMyMzM4NDA1LTY0NDJiNGFkMGZmMTI2NTY2NTYwZTJmNjA2NjFhYWJhZjNmOTI1NDNhNjFmYjI0NmZkMDJhMDIzZGRkMmU5ZDg) im Ladefuchs Channel
